### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [lukasbystricky/john-dewey_the-public-and-its-problems#1]
### General Issues:

- [x] Re-run `se clean .` and commit the changes.

### preface.xhtml:

- [x] Replace `z3998:sender` with `z3998:signature`.

### chapter-3.xhtml:

- [ ] Remove italics around `ex officio`. This is in M-W.

### chapter-4.xhtml:

- [x] Remove italics around `ad hoc` ([SEMOS 8.9.1](https://standardebooks.org/manual/1.7.1/single-page#8.9.1)).

### chapter-5.xhtml:

- [x] Remove italics around `ex post facto`. This is in M-W.

### chapter-6.xhtml:

- [ ] Remove italics from `par excellence`. This is in M-W.

### local.css:

- [x] Add:
```
[epub|type~="z3998:signature"]{
	font-variant: small-caps;
}
```

### content.opf:

- [x] Remove:
```
		<dc:contributor id="transcriber-1">Lukas Bystricky</dc:contributor>
		<meta property="file-as" refines="#transcriber-1">Bystricky, Lukas</meta>
		<meta property="role" refines="#transcriber-1" scheme="marc:relators">trc</meta>
```

You can add `<meta property="role" refines="#producer-1" scheme="marc:relators">trc</meta>` to your producer metadata instead.

**Comment by lukasbystricky** [comment]
Done everything except remove italics around par excellence; this is non-English confusable phrase according to lint.
